services:
  app:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19006:19006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true